apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deplpoy
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        
  replicas: 3
  selector:
    matchLabels:
      env: demo
      