apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # ""  indicates the core API group
  resources: ["pods"] # this specifies the resource type that the rule applies to
  verbs: ["get", "watch", "list"] # this specifies the allowed actions on the specified resources
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"] 